current = {
    'schema': False,
    'title': ['ds:prjTitle', 'ds:DatTitle'],
    'organization': 'ds:prjCoordinatorOrganization',
    'notes': ['ds:prjDescription', 'ds:DatDescription'],
    'license': ['ds:DatLicense'],
    'dataset_name': 'ds:DatName',
    'location': 'ds:prjTargetLocation',
    'latitude_map': 'ds:prjLatitude',
    'longitude_map': 'ds:prjLongitude',
    'start_date': ['ds:prjStartDate', 'ds:DatStartDate'],
    'end_date': ['ds:prjEndDate', 'ds:DatEndDate'],
    'dataset_type': 'ds:DatType',
    'sensor_type': 'ds:DatSensorType',
    'size': 'ds:DatSize',
    'dataset_format': 'ds:DatFileFormat',
    'number_participants': 'ds:prjSelectedParticipants',
    'language': 'ds:DatLanguage',
    'collection_name': ['ds:prjCollectionFacet'],
    'project_url': 'ds:prjURL',
    'category': ['ds:prjCategoryFacet', 'ds:DatCategoryFacet'],
    'domain': 'ds:DatDomain',
    '5_stars': 'ds:DatFiveStars',
    'publication_date': 'ds:DatPublicationTimestamp',
    'identifier': ['ds:prjIdentifier', 'ds:DatIdentifier'],
    'request_contact': 'ds:prjDownloadRequestEmail',
    'technical_report-name': 'ds:prjDocumentationName',
    'technical_report-url': 'ds:prjDocumentationURL',
    'technical_report-format': 'ds:prjDocumentationFormat',
    'codebook-name': 'ds:DatCodebookName',
    'codebook-url': 'ds:DatCodebookURL',
    'codebook-format': 'ds:DatCodebookFormat',
    'additional_material-name': 'ds:prjAdditionalMaterialName',
    'additional_material-url': 'ds:prjAdditionalMaterialUrl',
    'additional_material-format': 'ds:prjAdditionalMaterialFormat',
    'maintainer': False,
    'maintainer_email': 'ds:DatOwner',
    'data_origin': 'ds:DatOrigin',
    'duration_facet': ['ds:prjDurationFacet', 'ds:DatDurationFacet'],  # when create facets?
    'location_facet': ['ds:prjLocationFacet', 'ds:DatLocationFacet'],  # when create facets?
    'data_type_facet': ['ds:DataTypeFacet']  # when create facets?
}

project = {
    'ds:prjTitle': 'title',
    'ds:prjURL': 'project_url',
    'ds:prjKeywords': '',
    'ds:prjType': '',
    'ds:prjDescription': 'notes',
    'ds:prjStartDate': 'start_date',
    'ds:prjEndDate': 'end_date',
    'ds:prjFundingAgency': '',
    'ds:prjInput': '',
    'ds:prjOutput': '',
    'ds:prjCoordinator': '',
    'ds:prjObservations': '',
    'ds:prjCoordinatorOrganization': 'organization',
    'ds:prjProjectArea': '',
    'ds:prjMembers': '',
    'ds:prjTargetLocation': 'location',
    'ds:prjTargetPopulation': '',
    'ds:prjOverallParticipantsInvolved': '',
    'ds:prjSelectedParticipants': 'number_participants',
    'ds:prjTypeOfMeasurements': '',
    'ds:prjIRBApprovalDate': '',
    'ds:prjIRBApprovalOrganization': '',
    'ds:prjIRBApprovalNumber': '',
    'ds:prjCiteAs': '',
    'ds:prjMaintenance': '',
    'ds:prjLatitude': 'latitude_map',
    'ds:prjLongitude': 'longitude_map',
    'ds:prjThumbnailUrl': '',
    'ds:prjIdentifier': 'identifier',
    'ds:prjDownloadRequestEmail': 'request_contact',
    'ds:prjDurationFacet': 'duration_facet',
    'ds:prjLocationFacet': 'location_facet',
    'ds:prjCollectionFacet': 'collection_name',
    'ds:prjCategoryFacet': 'category',
    'ds:prjAdditionalMaterialName': 'additional_material-name',
    'ds:prjAdditionalMaterialUrl': 'additional_material-url',
    'ds:prjAdditionalMaterialFormat': 'additional_material-format',
    'ds:prjDocumentationName': 'technical_report-name',
    'ds:prjDocumentationURL': 'technical_report-url',
    'ds:prjDocumentationFormat': 'technical_report-format',
}

dataset = {
    'ds:DatName': {'column': 'dataset_name', 'fromProject': False},
    'ds:DatDescription': {'column': 'notes', 'fromProject': False},
    'ds:DatVersion': {'column': '', 'fromProject': False},
    'ds:DatPublicationTimestamp': {'column': 'publication_date', 'fromProject': False},
    'ds:DatLicense': {'column': '', 'fromProject': True},
    'ds:DatURL': {'column': '', 'fromProject': False},
    'ds:DatKeyword': {'column': '', 'fromProject': False},
    'ds:DatPublisher': {'column': '', 'fromProject': False},
    'ds:DatCreator': {'column': '', 'fromProject': False},
    'ds:DatOwner': {'column': 'maintainer_email', 'fromProject': False},
    'ds:DatLanguage': {'column': 'language', 'fromProject': False},
    'ds:DatLevel': {'column': '', 'fromProject': False},
    'ds:DatSize': {'column': 'size', 'fromProject': False},
    'ds:DatDomain': {'column': 'domain', 'fromProject': False},
    'ds:DatFileFormat': {'column': 'dataset_format', 'fromProject': False},
    'ds:DatDetailedDescription': {'column': '', 'fromProject': False},

    'ds:DatDownloadRequest': {'column': '', 'fromProject': False},
    'ds:DatConditionsOfAccess': {'column': '', 'fromProject': False},
    'ds:DatGenre': {'column': '', 'fromProject': False},
    'ds:DatisAccessibleForFree': {'column': '', 'fromProject': False},
    'ds:DatExpires': {'column': '', 'fromProject': False},
    'ds:DatType': {'column': 'dataset_type', 'fromProject': False},
    'ds:DatSensorType': {'column': 'sensor_type', 'fromProject': False},
    'ds:DatStartDate': {'column': 'start_date', 'fromProject': False},
    'ds:DatEndDate': {'column': 'end_date', 'fromProject': False},
    'ds:DatFiveStars': {'column': '5_stars', 'fromProject': False},
    'ds:DatOrigin': {'column': 'data_origin', 'fromProject': False},
    'ds:DatCreativeWorkStatus': {'column': '', 'fromProject': False},
    'ds:DatIdentifier': {'column': 'identifier', 'fromProject': False},
    'ds:DatChangelogURL': {'column': '', 'fromProject': False},
    'ds:DatLicenceURL': {'column': 'license', 'fromProject': True},
    'ds:DatSha256': {'column': '', 'fromProject': False},
    'ds:DatUpdateTimestamp': {'column': '', 'fromProject': False},
    'ds:DatBasedOn': {'column': '', 'fromProject': False},
    'ds:DatTitle': {'column': 'title', 'fromProject': False},
    'ds:DatSensorName': {'column': '', 'fromProject': False},

    'ds:DatDownloadRequestName': {'column': '', 'fromProject': True},
    'ds:DatDownloadRequestURL': {'column': '', 'fromProject': True},
    'ds:DatDownloadRequestFormat': {'column': '', 'fromProject': True},

    'ds:DatDocumentationName': {'column': '', 'fromProject': True},
    'ds:DatDocumentationURL': {'column': '', 'fromProject': True},
    'ds:DatDocumentationFormat': {'column': '', 'fromProject': True},
    'ds:DatCodebookName': {'column': 'codebook-name', 'fromProject': False},
    'ds:DatCodebookURL': {'column': 'codebook-url', 'fromProject': False},
    'ds:DatCodebookFormat': {'column': 'codebook-format', 'fromProject': False},
    'ds:DatAdditionalMaterialName': {'column': '', 'fromProject': True},
    'ds:DatAdditionalMaterialURL': {'column': '', 'fromProject': True},
    'ds:DatAdditionalMaterialFormat': {'column': '', 'fromProject': True},

    'ds:DatDurationFacet': {'column': 'duration_facet', 'fromProject': False},
    'ds:DatLocationFacet': {'column': 'location_facet', 'fromProject': False},
    'ds:DataTypeFacet': {'column': 'data_type_facet', 'fromProject': False},
    'ds:DatCategoryFacet': {'column': 'category', 'fromProject': False},
    
    # added not in excel: 
    'ds:DatLatitude': {'column': '', 'fromProject': True},
    'ds:DatLongitude': {'column': 'longitude_map', 'fromProject': True},

    # to remove
    # 'ds:DatAdditionalMaterial': {'column': '', 'fromProject': False},

}
