project = {
    'ds:prjTitle': 'title',
    'ds:prjURL': 'project_url',
    'ds:prjWebpage':'',
    'ds:prjKeywords': '',
    'ds:prjType': '',
    'ds:prjDescription': 'notes',
    'ds:prjStartDate': 'start_date',
    'ds:prjEndDate': 'end_date',
    'ds:prjFundingAgency': '',
    'ds:prjInput': '',
    'ds:prjOutput': '',
    'ds:prjCoordinator': '',
    'ds:prjObservations': '',
    'ds:prjCoordinatorOrganization': 'organization',
    'ds:prjProjectArea': '',
    'ds:prjMembers': '',
    'ds:prjTargetLocation': 'location',
    'ds:prjTargetPopulation': '',
    'ds:prjOverallParticipantsInvolved': '',
    'ds:prjSelectedParticipants': 'number_participants',
    'ds:prjTypeOfMeasurements': '',
    'ds:prjIRBApprovalDate': '',
    'ds:prjIRBApprovalOrganization': '',
    'ds:prjIRBApprovalNumber': '',
    'ds:prjCiteAs': '',
    'ds:prjMaintenance': '',
    'ds:prjLatitude': 'latitude_map',
    'ds:prjLongitude': 'longitude_map',
    'ds:prjThumbnailURL': '',
    'ds:prjIdentifier': 'identifier',
    'ds:prjDownloadRequestEmail': 'request_contact',

    'ds:prjAdditionalMaterialName': 'additional_material-name',
    'ds:prjAdditionalMaterialURL': 'additional_material-url',
    'ds:prjAdditionalMaterialFormat': 'additional_material-format',
    'ds:prjDocumentationName': 'technical_report-name',
    'ds:prjDocumentationURL': 'technical_report-url',
    'ds:prjDocumentationFormat': 'technical_report-format',


    'ds:prjDurationFacet': 'duration_facet',
    'ds:prjLocationFacet': 'location_facet',
    'ds:prjCollectionFacet': 'collection_name',
    'ds:prjCategoryFacet': 'category',

    'ds:prjIsVisible': '',
}

dataset = {
    'ds:DatName': 'title',
    'ds:DatDescription': 'notes',
    'ds:DatVersion': '',
    'ds:DatPublicationTimestamp': 'publication_date',
    'ds:DatLicense': '',
    'ds:DatURL': '',
    'ds:DatKeyword': '',
    'ds:DatPublisher': '',
    'ds:DatCreator': '',
    'ds:DatOwner': 'maintainer_email',
    'ds:DatLanguage': 'language',
    'ds:DatLevel': '',
    'ds:DatSize': 'size',
    'ds:DatDomain': 'domain',
    'ds:DatFileFormat': 'dataset_format',
    'ds:DatDetailedDescription': '',
    'ds:DatDownloadRequest': '',
    'ds:DatConditionsOfAccess': '',
    'ds:DatGenre': '',
    'ds:DatisAccessibleForFree': '',
    'ds:DatExpires': '',
    'ds:DatType': 'dataset_type',
    'ds:DatSensorType': 'sensor_type',
    'ds:DatStartDate': 'start_date',
    'ds:DatEndDate': 'end_date',
    'ds:DatFiveStars': '5_stars',
    'ds:DatOrigin': 'data_origin',
    'ds:DatCreativeWorkStatus': '',
    'ds:DatDownloadRequestName': '',
    'ds:DatDownloadRequestURL': '',
    'ds:DatDownloadRequestFormat': '',
    'ds:DatCodebookName': 'codebook-name',
    'ds:DatCodebookURL': 'codebook-url',
    'ds:DatCodebookFormat': 'codebook-format',
    'ds:DatAdditionalMaterialName': '',
    'ds:DatAdditionalMaterialURL': '',
    'ds:DatAdditionalMaterialFormat': '',
    'ds:DatIdentifier': 'identifier',
    'ds:DatChangelogURL': '',
    'ds:DatLicenceURL': 'license',
    'ds:DatSha256': '',
    'ds:DatUpdateTimestamp': '',
    'ds:DatBasedOn': '',
    'ds:DatSensorName': 'dataset_name',
    'ds:DatIsVisible': '',

    'ds:DatDurationFacet': 'duration_facet',
    'ds:DatLocationFacet': 'location_facet',
    'ds:DataTypeFacet': 'data_type_facet',
    'ds:DatCategoryFacet': 'category',
}
